on:
  push:
  workflow_dispatch:

jobs:
  get-branch-name:
    runs-on: 
      - ubuntu-latest

    steps:
      - name: 'Print Branch Name'
        run: |
          echo ${{ toJSON(github.ref_name) }}
