name: 'Deploy (dev, test, platform)'

env:
  environment: ${{ github.event_name == 'workflow_dispatch' && 'wf_dp' || toJson(github.event.inputs.environment) }} 

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - 'test'
          - 'platform'
        description: 'Deploy to environment'
        required: true
        default: test
  push:
    branches:
      - main
    # paths-ignore:
    #   - '.github/workflows/**'

jobs:
  detect-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: 'detect trigger'
        run: |
          echo ${{ env.environment }}
