name: 'Deploy (dev, test, platform)'

env:
  environment: ${{ toJson(github.event_name) == 'workflow_dispatch' && 'wf_dp' || 'push' }} 

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # paths-ignore:
    #   - '.github/workflows/**'

jobs:
  detect-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: 'detect trigger'
        run: |
          echo ${{ env.environment }}
