name: Deploy (dev/test/platform)

run-name: Deploy to ${{ github.event_name == 'push' && "dev" || toJson(github.event.inputs.environment) }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - 'dev'
          - 'test'
          - 'platform'
        description: 'Deploy to environment'
        required: true
        default: test
  push:
    branches:
      - main
    # paths-ignore:
    #   - '.github/workflows/**'

env:
  environment: ${{ github.event_name == 'push' && 'dev' || toJson(github.event.inputs.environment) }} 

jobs:
  detect-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: 'detect trigger'
        run: |
          echo ${{ env.environment }}
