name: Release

on:
  push:
    tags:
    #Staging
      - '^.*[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+'
    #Production
      - '^.*[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  release:
    runs-on:
      - ubuntu-latest

    steps:
      - name: 'Print environment.'
        env:
          release_env: ${{ contains(github.ref_name, '-rc') && 'staging' || 'prod' }}
        run: |
          echo $release_env
