name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
      - 'release/*/[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  release:
    runs-on:
      - ubuntu-latest

    steps:
      - name: 'Event Payload'
        run: echo ${{ github.events }}
