name: 'Deploy'

on:
  workflow_call:
    inputs:
      environment: 
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        sub_environments: ${{ fromJSON(vars.SUB_ENVIRONMENTS)[inputs.environment] }}

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: "Deploy to ${{ matrix.sub_environments }}"
        run: |
          echo ${{ matrix.sub_environments }}