name: 'Deploy'

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      environment: 
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        sub_environments: ${{ fromJSON(vars.SUB_ENVIRONMENTS)[inputs.environment] }}
      max-parallel: 1

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: 'Debug'
        run: |
          ls -la

      - name: "Deploy to ${{ matrix.sub_environments }}"
        run: |
          echo ${{ matrix.sub_environments }}